### ISSUE TITLE
greenkeeper-lockfile makes build fail (node 8)

### ISSUE THREAD

**Issue by nikolas** [greenkeeperio/greenkeeper-lockfile#196] opened 2018-08-15 14:09 UTC
Hi,
greenkeeper-lockfile is throwing an error on this build:
https://travis-ci.org/ccnmtl/econplayground.js/jobs/415978779

```
node_modules/builtin-status-codes/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/cacache/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/cache-base/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/caller-path/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/callsites/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/camelcase/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/caniuse-lite/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
/home/travis/.nvm/versions/node/v8.11.3/lib/node_modules/greenkeeper-lockfile/update.js:64
    process.chdir(lockfilePath)
            ^
Error: ENOENT: no such file or directory, uv_chdir
    at allPackageFiles.reduce (/home/travis/.nvm/versions/node/v8.11.3/lib/node_modules/greenkeeper-lockfile/update.js:64:13)
    at Array.reduce (<anonymous>)
    at Module.update [as exports] (/home/travis/.nvm/versions/node/v8.11.3/lib/node_modules/greenkeeper-lockfile/update.js:61:36)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v8.11.3/lib/node_modules/greenkeeper-lockfile/update.js:110:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
The command "greenkeeper-lockfile-update" failed and exited with 1 during .
```

**Comment by wolfy1339** [comment] 2018-08-27 20:17
I have the same issue, but with a different directory. This is a duplicate of #194

**Comment by janl** [comment] 2018-09-13 10:03
closing as dupe.

**Closed by janl** 2018-09-13 10:03 UTC
